global:
  resolve_timeout: 30s
route:
  receiver: local
  group_by: [alertname]
  group_wait: 5s
  group_interval: 15s
  repeat_interval: 4h
receivers:
  - name: local
inhibit_rules:
  - source_matchers: ['alertname="PgSentryEtcdQuorumLost"']
    target_matchers: ['alertname="PgSentryEtcdMemberDown"']
    equal: []
